### ISSUE TITLE
Not using `Box<dyn Error>`

### ISSUE THREAD

**Issue by TheNeikos** [sumibi-yakitori/ldtk2-rs#3]
Currently all load mechanisms use `Box<dyn Error>`. This has some issues, as for example it is not `Send + Sync`. The other is that the error kind is completely opaque and one would need to do code inspection to find out what the possible errors are.

My suggestion would be to either expose the `serde_json` errors, which would solve this issue directly. Or use a crate like `anyhow` that at least has some more bounds on the error type and allows for more flexibility.

What do you think?

**Comment by sumibi-yakitori** [comment]
Hi.
I think both of the suggestions you made are good suggestions.

It is true that if I use this crate as it is now for background loading, etc., I will have problems.

I would like to change it to expose the `serde_json` errors.

**Comment by TheNeikos** [comment]
Thanks!
